# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/imagebuilder:x86-64-22.03.2
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Install Package
      run: |
        sudo apt update
        sudo apt install -y jq
    - name: Download ipk
      run: sh download.sh
    - name: Move ipk
      run: |
        mv luci-app-openclash.ipk /home/build/openwrt/packages
    - name: Make Image
      env:
        rootfs_size: 2048
        kernel_size: 256
        profile: generic
        packages: amd64-microcode base-files bash bnx2-firmware bridge busybox bzip2 ca-bundle 
                    ca-certificates cgi-io coreutils coreutils-nohup curl dnsmasq-full dropbear e2fsprogs 
                    file firewall frpc frps fstools fwtool getrandom golang golang-src grub2 grub2-efi gzip 
                    htop hwinfo intel-microcode ip-full ip6tables iperf iperf3 ipset iptables iptables-mod-extra 
                    iptables-mod-tproxy jshn jsonfilter kernel keyctl keyutils kmod-asn1-decoder 
                    kmod-ata-core kmod-bnx2 kmod-button-hotplug kmod-crypto-acompress kmod-crypto-aead 
                    kmod-crypto-authenc kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-gcm kmod-crypto-gf128 
                    kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-hw-ccp kmod-crypto-kpp 
                    kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 
                    kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md4 
                    kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-rsa 
                    kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha512 kmod-e1000 
                    kmod-e1000e kmod-forcedeth kmod-fs-ext4 kmod-fs-vfat kmod-geneve kmod-gre kmod-hwmon-core 
                    kmod-hwmon-drivetemp kmod-i2c-algo-bit kmod-i2c-core kmod-igb kmod-igc kmod-input-core 
                    kmod-ip6tables kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-extra 
                    kmod-ipt-ipset kmod-ipt-nat kmod-ipt-offload kmod-ipt-tproxy kmod-iptunnel kmod-ixgbe 
                    kmod-lib-crc-ccitt kmod-lib-crc16 kmod-lib-crc32c kmod-lib-lzo kmod-libphy kmod-mdio 
                    kmod-mii kmod-mlx4-core kmod-mlx5-core kmod-mmc kmod-nf-conntrack kmod-nf-conntrack-netlink 
                    kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-nat kmod-nf-nat6 kmod-nf-reject 
                    kmod-nf-reject6 kmod-nfnetlink kmod-nls-base kmod-nls-cp437 kmod-nls-iso8859-1 kmod-nls-utf8 
                    kmod-nsh kmod-openvswitch kmod-openvswitch-geneve kmod-openvswitch-gre kmod-openvswitch-vxlan 
                    kmod-phy-realtek kmod-ppp kmod-pppoe kmod-pppox kmod-pps kmod-ptp kmod-r8169 kmod-random-core 
                    kmod-scsi-core kmod-slhc kmod-swconfig kmod-tcp-bbr kmod-tcp-hybla kmod-tun kmod-udptunnel4 
                    kmod-udptunnel6 kmod-usb-core kmod-usb-ehci kmod-usb-net kmod-usb-storage kmod-usb-storage-extras 
                    kmod-usb-storage-uas kmod-usb-uhci kmod-usb-wdm kmod-usb2 kmod-usb2-pci kmod-usb3 kmod-vxlan 
                    kmod-wireguard kmod-zram libblkid libblobmsg-json libbpf libbz2 libc libcap libcap-bin libcomerr 
                    libcurl libdb47 libelf libevent2 libext2fs libf2fs libgcc libgd libgmp libip4tc libip6tc libipset 
                    libiwinfo-data libiwinfo-lua libiwinfo libjpeg-turbo libjson-c libjson-script libkeyutils liblua 
                    liblucihttp-lua liblucihttp liblz4 liblzma libmagic libmnl libncurses libnetfilter-conntrack 
                    libnettle libnfnetlink libnghttp2 libnl-tiny libopenssl libpcap libpcre libpng libpthread libreadline 
                    librt libruby libsmartcols libss libubox libubus-lua libubus libuci libuclient libustream-wolfssl 
                    libuuid libuv libwebp libwolfssl libwolfssl libxtables libyaml libzip-openssl libzstd logd lscpu 
                    lua luci luci-app-acl luci-app-firewall luci-app-frpc luci-app-frps luci-app-ntpc luci-app-openclash 
                    luci-app-opkg luci-app-smartdns luci-app-wireguard luci-base luci-compat luci-i18n-acl-en luci-i18n-acl-zh-cn 
                    luci-i18n-acl-zh-tw luci-i18n-base-en luci-i18n-base-zh-cn luci-i18n-base-zh-tw luci-i18n-firewall-en 
                    luci-i18n-firewall-zh-cn luci-i18n-firewall-zh-tw luci-i18n-frpc-en luci-i18n-frpc-zh-cn 
                    luci-i18n-frpc-zh-tw luci-i18n-frps-en luci-i18n-frps-zh-cn luci-i18n-frps-zh-tw luci-i18n-ntpc-en 
                    luci-i18n-ntpc-zh-cn luci-i18n-ntpc-zh-tw luci-i18n-opkg-en luci-i18n-opkg-zh-cn luci-i18n-opkg-zh-tw 
                    luci-i18n-smartdns-zh-cn luci-i18n-wireguard-en luci-i18n-wireguard-zh-cn luci-i18n-wireguard-zh-tw 
                    luci-lib-base luci-lib-ip luci-lib-json luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-dashboard 
                    luci-mod-network luci-mod-rpc luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp 
                    luci-proto-wireguard luci-ssl luci-theme-bootstrap luci-theme-material luci-theme-openwrt luci-theme-openwrt-2020 
                    lz4 mkf2fs mtd nano netdata netifd ntpclient odhcp6c odhcpd-ipv6only openwrt-keyring opkg partx-utils ppp 
                    ppp-mod-pppoe procd procps-ng procps-ng-ps px5g-wolfssl r8169-firmware resize2fs rpcd rpcd-mod-file rpcd-mod-iwinfo 
                    rpcd-mod-luci rpcd-mod-rrdns ruby ruby-yaml smartdns swconfig tar terminfo tmux ubox ubus 
                    ubusd uci uclient-fetch uhttpd uhttpd-mod-ubus unzip urandom-seed urngd usign vim wget-ssl whois 
                    wireguard-tools xz xz-utils zlib zoneinfo-africa zoneinfo-asia zoneinfo-atlantic zoneinfo-australia-nz 
                    zoneinfo-core zoneinfo-europe zoneinfo-india zoneinfo-northamerica zoneinfo-pacific zoneinfo-poles 
                    zoneinfo-simple zoneinfo-southamerica zram-swap -dnsmasq -firewall4
      run: |
        cd /home/build/openwrt
        chown -R build:build /home/build/openwrt/packages
        sudo -u build sed -i "s/CONFIG_TARGET_ROOTFS_PARTSIZE=[0-9]\+/CONFIG_TARGET_ROOTFS_PARTSIZE=${{ env.rootfs_size }}/g;s/CONFIG_TARGET_KERNEL_PARTSIZE=[0-9]\+/CONFIG_TARGET_KERNEL_PARTSIZE=${{ env.kernel_size }}/g" .config
        sudo -u build make image PROFILE=${{ env.profile }} PACKAGES="${{ env.packages }}"
        tar zcvf openwrt-x86-64-master.tar.gz bin/targets/x86/64/*
    - uses: actions/upload-artifact@v3
      with:
          name: openwrt
          path: /home/build/openwrt/openwrt-x86-64-master.tar.gz
